# Generated by Django 5.0.6 on 2024-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='idcapteur',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
