# Generated by Django 5.0.6 on 2024-06-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_capteur_idcapteur_alter_capteur_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donnees',
            old_name='idcapteur',
            new_name='capteur',
        ),
    ]
